### PR TITLE
Trial: Add deprecated annotation in kotlin-spring

### PR DESCRIPTION
**Pull request by yutaka0m**
First trial Pull Request

I want to embed "@Deprecated" annotation when `deprecated: true` in `kotlin-spring`

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/openapitools/openapi-generator/blob/master/CONTRIBUTING.md).
- [x] If contributing template-only or documentation-only changes which will change sample output, [build the project](https://github.com/OpenAPITools/openapi-generator#14---build-projects) before.
- [x] Run the shell script(s) under `./bin/` (or Windows batch scripts under`.\bin\windows`) to update Petstore samples related to your fix. This is important, as CI jobs will verify _all_ generator outputs of your HEAD commit, and these must match the expectations made by your contribution. You only need to run `./bin/{LANG}-petstore.sh`, `./bin/openapi3/{LANG}-petstore.sh` if updating the code or mustache templates for a language (`{LANG}`) (e.g. php, ruby, python, etc).
- [x] File the PR against the [correct branch](https://github.com/OpenAPITools/openapi-generator/wiki/Git-Branches): `master`, `4.3.x`, `5.0.x`. Default: `master`.
- [ ] Copy the [technical committee](https://github.com/openapitools/openapi-generator/#62---openapi-generator-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### CODE REVIEW

**Comment by yutaka0m** [comment]
mvn clean install でエラーが起きる。。。

`Error fetching link: /Users/abi01073/PrivateDevelop/ackintosh/openapi-generator/modules/openapi-generator/Users/abi01073/PrivateDevelop/ackintosh/openapi-generator/modules/openapi-generator-cli/target/apidocs. Ignored it.
`

**Comment by ackintosh** [comment]
僕もmvn clean installを試しましたが、正常終了しました 😺

**Comment by ackintosh** [comment]
僕も同じエラーがでました...! 
とりあえず、masterでも出るので今回の修正とは関係なさそうですね 💡 maven-javadoc-plugin が何かおかしいのか??

**Comment by yutaka0m** [comment]
そうですか、よかった！

私も「あれ」と思ってmasterでやったらダメでした。
日曜日は大丈夫だったので、最近の話だと思います。

**Pull request closed without merging**
